// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38C7v7wvLXICTGPxJWwpqnQUYPSaiBG0',
    appId: '1:394175121263:web:67e648c57a4ffbe4ea8a9a',
    messagingSenderId: '394175121263',
    projectId: 'reservation-db-39a59',
    authDomain: 'reservation-db-39a59.firebaseapp.com',
    storageBucket: 'reservation-db-39a59.firebasestorage.app',
    measurementId: 'G-V5CZGR6FBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR09Mci5PZyJDbpq6_fZyYTiHtqBultGs',
    appId: '1:394175121263:android:1d3ed6cefb5bc8d8ea8a9a',
    messagingSenderId: '394175121263',
    projectId: 'reservation-db-39a59',
    storageBucket: 'reservation-db-39a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY2SZqfV2FlbEdZkG2QjE_VrJbiZa7q8c',
    appId: '1:394175121263:ios:7fe8307ecfaa7c96ea8a9a',
    messagingSenderId: '394175121263',
    projectId: 'reservation-db-39a59',
    storageBucket: 'reservation-db-39a59.firebasestorage.app',
    iosClientId: '394175121263-hek6p5bto88edqjgdv18ekjormjqpm69.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbershoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY2SZqfV2FlbEdZkG2QjE_VrJbiZa7q8c',
    appId: '1:394175121263:ios:7fe8307ecfaa7c96ea8a9a',
    messagingSenderId: '394175121263',
    projectId: 'reservation-db-39a59',
    storageBucket: 'reservation-db-39a59.firebasestorage.app',
    iosClientId: '394175121263-hek6p5bto88edqjgdv18ekjormjqpm69.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbershoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38C7v7wvLXICTGPxJWwpqnQUYPSaiBG0',
    appId: '1:394175121263:web:f5186e1613897426ea8a9a',
    messagingSenderId: '394175121263',
    projectId: 'reservation-db-39a59',
    authDomain: 'reservation-db-39a59.firebaseapp.com',
    storageBucket: 'reservation-db-39a59.firebasestorage.app',
    measurementId: 'G-N6V7SM5JX6',
  );
}
